import type { Metadata } from "next";
import { Space_Mono, Work_Sans, Cormorant_Garamond, Caveat, Inter } from "next/font/google";

import "./globals.css";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const font = `${spaceMono.variable} ${workSans.variable} ${cormorantGaramond.variable} ${caveat.variable} ${inter.variable}`;

export const metadata: Metadata = {
  title: "Black sheep goes wild",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${font} h-full antialiased`}>
      <body className="min-h-full">{children}</body>
    </html>
  );
}
